### ISSUE TITLE
Extend `get_vpts()` to provide access to the RMI CROW dataset

### ISSUE THREAD

**Issue by peterdesmet** [aloftdata/getRad#13]
## Source

I suggest the value `rmi` for the parameter `source`: `rmi`. It is the only VPTS dataset by RMI. I think the alternative value `crow` would be confusing as a name, since that is also used for the visualization.

## Scope

Metadata and context can be found [here](https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW). The dataset covers 10 radars and has data since 2019. More data are added daily.

- [ ] Do we have a mechanism for users to discover the scope (temporal + radars) of dataset?

## Data files

Data files are deposited at https://opendata.meteo.be/ftp/observations/radar/vbird/ and organized in radar and year directories. The file names are of the format `<radar>_vpts_<yyyymmdd>.txt` (e.g. `behel_vpts_20191015.txt`)

## Data format

The data format is the default stdout of **vol2bird**, which is fixed width ([example](https://opendata.meteo.be/ftp/observations/radar/vbird/behel/2019/behel_vpts_20191015.txt)). If you write a parser for that format, I would call it vol2bird_vpts, not rmi_vpts. The CROW visualization has a [minimal parser](https://github.com/inbo/crow/blob/a17e13373e2442b9b9d5ff374863e49f222a6916/src/helpers.ts#L159-L183)

The format unfortunately does not contain all columns of VPTS CSV. Below is a suggestion how it could be completed.

- [x] radar: value provided by user
- [x] datetime: columns `<date>T<time>00Z`
- [x] height: `< HGHT>`
- [x] u: `<u>`
- [x] v: `<v>`
- [x] w: `<w>`
- [x] ff: `<ff>`
- [x] dd: `<dd>`
- [x] sd_vvp: `<sd_vvp>`
- [x] gap: `<gap>`
- [x] eta: `<eta>`
- [x] dens: `<dens>`
- [x] dbz: `<dbz>`
- [x] dbz_all: `<DBZH>`
- [x] n: `<n>`
- [x] n_dbz: `<dbz>`
- [x] n_all: `<n_all>`
- [x] n_dbz_all: `<n_dbz_all>`
- [x] rcs: very likely `11`, but it's not recorded and not a required term
- [x] sd_vvp_threshold: very likely `2`, but it's not recorded and not a required term
- [ ] vcp: leave empty
- [x] radar_latitude: required term, not recorded. I suggest to retrieve that from the radar overview, see suggested function at #6
- [x] radar_longitude: same issue `radar_latitude`
- [x] radar_height: same issue `radar_latitude`
- [x] radar_wavelength: same issue `radar_latitude`
- [x] source_file: not a required term. Recorded in the csv comments, as eg. `# polar volume input: /tmp/20191015143000.rad.behel.pvol.dbzh.scanz.pvol.h5`

----

## Todo

- [x] Handle radar datetime combinations not present on RMI: write cli error class
- [x] Increase coverage for `get_vpts_rmi()`
- [x] Enrich tibble with `dplyr::left_join()` with `weather_radars()`
- [ ] Handle interval filtering in `get_vpts()` for both helpers: dry
- [x] move coverage error handling away from `get_vpts()`? new helper? to `get_vpts_aloft()`?
- [x] rename `vpts_from_s3` to more general term, and add `switch()` statement based on source to select the correct `get_vpts_*` helper
- [ ] check order of columns being returned out of `get_vpts()`

**Comment by bart1** [comment]
arrow actually looks quite cool I need to look into that!

**Comment by peterdesmet** [comment]
> 1. Is the metadata header always the same length?

Do you mean: the same amount of rows? Not sure, but they should always start with `#`, which can be ignored with `readr:: read_fwf(comment = "#")`

> 2. Are the columns always the same width and order?

Yes

**Comment by PietrH** [comment]
> > 1. Is the metadata header always the same length?
> 
> Do you mean: the same amount of rows? Not sure, but they should always start with `#`, which can be ignored with `readr:: read_fwf(comment = "#")`

Sadly the header is also commented out, but if we are very certain the columns never change, this shouldn't be an issue.

**Comment by bart1** [comment]
Also see: https://github.com/tidyverse/vroom/issues/551

**Comment by PietrH** [comment]
> > > 1. Is the metadata header always the same length?
> > 
> > 
> > Do you mean: the same amount of rows? Not sure, but they should always start with `#`, which can be ignored with `readr:: read_fwf(comment = "#")`
> 
> Sadly the header is also commented out, but if we are very certain the columns never change, this shouldn't be an issue.

The columns are always in the same order. 

There might be metadata that we want to preserve, like radar lat or long

**Comment by peterdesmet** [comment]
We currently use `get_vpts(source = "rmi")` to get data from https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW

At the meeting, @barthoekstra noted that `"rmi"` is not a very unique name. I'm in favour of keeping it as `source` value though:

- RMI is the official English acronym for the [Royal_Meteorological_Institute of Belgium](https://en.wikipedia.org/wiki/Royal_Meteorological_Institute). That institute is the source of the above VPTS dataset
- It doesn't clash with KMNI, which is the English acronym used to refer to [Royal Netherlands Meteorological Institute](https://en.wikipedia.org/wiki/Royal_Netherlands_Meteorological_Institute)
- The alternative would be to use the official identifier of the dataset, which is `RMI_DATASET_CROW`. That is rather long and uppercased.
- The datasets also lists `crow` as a resource identifier, but I think that is too easy to confuse with the visualisation tool of the same name.

Thoughs?

**Comment by peterdesmet** [comment]
> bit more explanation in the vignette:

We currently have:

https://github.com/aloftdata/getRad/blob/34fb4fcaa5f19d4c6426fbbd776c8c85e865e0a2/vignettes/supported_sources.Rmd#L104-L112

`get_vpts()` refers to this vignette.

**Comment by PietrH** [comment]
> > We currently use `get_vpts(source = "rmi")` to get data from https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW
> > At the meeting, [@barthoekstra](https://github.com/barthoekstra) noted that `"rmi"` is not a very unique name. I'm in favour of keeping it as `source` value though:
> > ```
> > * RMI is the official English acronym for the [Royal_Meteorological_Institute of Belgium](https://en.wikipedia.org/wiki/Royal_Meteorological_Institute). That institute is the source of the above VPTS dataset
> > 
> > * It doesn't clash with KMNI, which is the English acronym used to refer to [Royal Netherlands Meteorological Institute](https://en.wikipedia.org/wiki/Royal_Netherlands_Meteorological_Institute)
> > 
> > * The alternative would be to use the official identifier of the dataset, which is `RMI_DATASET_CROW`. That is rather long and uppercased.
> > 
> > * The datasets also lists `crow` as a resource identifier, but I think that is too easy to confuse with the visualisation tool of the same name.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thoughs?
> 
> Currently were mixing kind of two levels or sources (data provider (aloft and rmi) and dataset within provider (e.g. uva and baltrad)). At the moment it is fine but if we get data providers that over many more dataset (e.g. multiple processing settings) this might become more tricky. Maybe at some stage we need to move the dataset argument to provider specific functions, I think we can leave this for the future. I'm not so much against RMI I think any one word name will not cover the details. I think we should rather have a bit more explanation in the vignette and `?get_vpts`

I have already designed `get_vpts()` to use provider specific functions, `get_vpts()` really only does argument and some error handling before using `switch()` to direct to `get_vpts_aloft()` or ´get_vpts_rmi()´. It's possible for `get_vpts()` to inherit documentation from these helpers. I did it this way because I think it makes sense for users to use a single function to retrieve a single type of data, just like `get_pvol()`.

**Comment by PietrH** [comment]
> We currently use `get_vpts(source = "rmi")` to get data from https://opendata.meteo.be/geonetwork/srv/eng/catalog.search#/metadata/RMI_DATASET_CROW
> 
> At the meeting, [@barthoekstra](https://github.com/barthoekstra) noted that `"rmi"` is not a very unique name. I'm in favour of keeping it as `source` value though:
> 
>     * RMI is the official English acronym for the [Royal_Meteorological_Institute of Belgium](https://en.wikipedia.org/wiki/Royal_Meteorological_Institute). That institute is the source of the above VPTS dataset
> 
>     * It doesn't clash with KMNI, which is the English acronym used to refer to [Royal Netherlands Meteorological Institute](https://en.wikipedia.org/wiki/Royal_Netherlands_Meteorological_Institute)
> 
>     * The alternative would be to use the official identifier of the dataset, which is `RMI_DATASET_CROW`. That is rather long and uppercased.
> 
>     * The datasets also lists `crow` as a resource identifier, but I think that is too easy to confuse with the visualisation tool of the same name.
> 
> 
> Thoughs?

I understand Barts comment, but since I don't have a better alternative I'm also in favour of keeping `source = "rmi"`.

**Comment by peterdesmet** [comment]
Nice, I have move merged that info with the renamed vignette file.
